name: untitled10
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  firebase_auth: ^4.7.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  provider: ^6.0.5
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  firebase_auth: ^4.7.1
  firebase_analytics: ^10.4.4
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  shimmer: ^3.0.0
  like_button: ^2.0.5
  webview_flutter: ^4.2.2
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.8.4
  fluttertoast: ^8.2.2
  firebase_messaging: ^14.6.5

flutter:
  uses-material-design: true


# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/img.png
  branding: assets/icon/img.png
  color_dark: "#121212"
  image_dark: assets/icon/img.png
  branding_dark: assets/icon/img.png

  android_12:
    image: assets/icon/img.png
    icon_background_color: "#ffffff"
    image_dark: assets/icon/img.png
    icon_background_color_dark: "#121212"

  web: false